### ISSUE TITLE
Event ID 2001 (published post) reported when coupon is created

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#161]
When a coupon is created the plugin correctly reports event ID 9063 but also incorrectly reports event ID 2001:

![image](https://user-images.githubusercontent.com/3965050/161896370-5660f41f-9835-444c-a7c5-1f833fcecbd0.png)

**Comment by DannyWPWS** [comment]
Closing this up as this is resolved

**Comment by robert81** [comment]
I just tested this update this morning (the develop branch) and the issue persists:

![image](https://user-images.githubusercontent.com/3965050/165678612-26e21c74-ae6d-4e30-904a-d2399773a4b0.png)

**Comment by DannyWPWS** [comment]
Well, typically iv just created a test with develop etc (using the free current release of WSAL) and simply dont see this - 

![image](https://user-images.githubusercontent.com/59394454/165715522-7019239c-7ef0-484b-a20d-5cbf99b794b9.png)

Ill check your test site to see whats going on, but im sorry about this whatever is causing it

**Comment by DannyWPWS** [comment]
Iv been trying to make this happen with both free and premium and its not happening sadly

![image](https://user-images.githubusercontent.com/59394454/165746044-18db1d9c-9584-44fe-ba23-1a97d46dce3f.png)

**Comment by DannyWPWS** [comment]
Ok can confirm im seeing it with coupons at least so will see if there is anything that can be done from the extensions POV

**Comment by DannyWPWS** [comment]
Right ok - this is addressed in the upcoming WSAL release 

Event 2001 when making a coupon is fixed here https://github.com/wpwhitesecurity/wp-security-audit-log-premium/pull/2514/files

The overall issue of WSAL ignoring the CPTs we want it to is to be addressed here https://github.com/wpwhitesecurity/wp-security-audit-log-premium/issues/2515 which will solve 2100 when making a coupon etc

Ill leave this open however untill its fully addressed in WSAL
